9oormthon-univ/2024_DANPOON_TEAM_36_FE

- src/components/Inputs.js
- src/components/Upload/FileUpload.js
- src/components/Upload/UploadButton.js
- src/pages/Upload.js
- Upload 페이지 ui 구현
- Upload 페이지 내 사용 컴포넌트 구현
- Inputs.js Input 요소 재사용 컴포넌트화
#8
> Feat(Upload.js) : Upload 페이지 구현, Input 요소 컴포넌트화

- package-lock.json
- package.json
- src/components/InputUpload.js
- src/constants/InputMessage.js
- src/pages/Upload.js
- 빌드시 발생 부분 해결 : 캐시 삭제
- 추가 컴포넌트 작업
- 상수 메세지 선언
> Fix(Upload.js) : 빌드 에러 해결, 컴포넌트 추가 / docs : 상수 메세지 추가

- src/components/Signup/Checkbox.js
- src/components/Signup/RadioComponents.js
- src/pages/Signup.js
- Signup 페이지 ui 구현, 기능 구현 시도
- 사용 요소 컴포넌트화
- Signup API 연동 준비
#35
> feat(Signup.js) : Signup 페이지 ui, 기능 구현 시도, api 준비

- src/apis/Auth/getLogin.js
- src/apis/Board/addBoardLike.js
- src/apis/Board/cancelBoardLike.js
- src/apis/Board/deleteBoard.js
- src/apis/Board/saveBoard.js
- src/apis/Board/updateBoard.js
- src/apis/Comment/deleteComment.js
- src/apis/Comment/saveComment.js
- src/apis/Comment/updateComment.js
- src/apis/Feed/deleteFeed.js
- src/apis/Feed/getAllFeeds.js
- src/apis/Feed/uploadImage.js
- src/apis/Gpt/createSummit.js
- src/apis/Gpt/isValidModel.js
- src/apis/Gpt/selectPrompt.js
- src/apis/Investment/addBoardLike1.js
- src/apis/Investment/cancelBoardLike1.js
- src/apis/Member/getMyInfo.js
- src/apis/Member/saveAdditionalInfo.js
- src/apis/Member/updateInfo.js
- src/apis/Member/withdrawMember.js
- src/apis/axios.js
- 구현되어있는 API들을 메소드로 제작
- axiosClient 제작
> feat : apis

- src/components/MyPage/Info.js
- src/components/MyPage/LikePTVideo.js
- src/components/MyPage/VideoWrapper.js
- src/constants/MypageMessage.js
- src/pages/Mypage.js
- src/pages/Signup.js
> Feat#15 signup UI

- src/components/MyPage/Info.js
- src/components/MyPage/PTList.js
- src/pages/Mypage.js
> fix, feat<MyPage>UI추가작업및컴포넌트화

- src/components/OngoingSummit/Carousel.js
- src/components/OngoingSummit/UploadSuggestion.js
- src/pages/OngoingSummit.js
- src/theme.js
- OngoingSummit 페이지 세부 ui 수정
- 컴포넌트 추가, 변경
- theme.js 색상 추가
> style(OngoingSummit.js) : OngoingSummit 페이지 세부 ui 수정

- src/components/NavigationBar.js
> feat, style(Navigation.js) : css, 텍스트 변화 추가 작업

- src/constants/ModalMessage.js
- src/pages/Upload.js
- Upload 페이지 필수 요소 미입력시 Modal 창 출력 구현
> feat(Upload.js) : 필수 요소 미입력 시 Modal 창 출력 구현

- src/components/NavigationBar.js
Navigation 컴포넌트 로그인 유무에 따른 상태변화
> feat(Navigation.js) : 네비게이션 바 컴포넌트 로그인 상태 변화

- src/constants/LikePTVideoMockup.js
- src/constants/MypageMockup.js
- src/pages/Mypage.js
- docs : LikePTVideo, MypageMockup 데이터 작업
- fix : Mypage.js api 연동 테스트 작업 error 해결
#34
> docs, fix : mockData 작업, Mypage api 테스트 코드 작업 error 해결

- package-lock.json
- package.json
- src/pages/OngoingSummit.js
- src/routes.js
fix : recoil, not module error
> fix : recoil 관련 error, not module error

- src/components/PT/CommentInputWithSubmit.js
> style(PT.js) : comment style edit

- src/App.js
- src/apis/Board/saveBoard.js
- src/apis/Board/updateBoard.js
- src/pages/Upload.js
- saveBoard.js : upload 페이지에서 첫 업로드 api
- getMyBoard.js : pt 페이지에서 수정 클릭시 api
- updateBoard.js : pt 페이지에서 수정 클릭시 api 받고 수정내용 post
> feat(Upload.js) : upload 페이지 api 작업 진행

- src/components/MyPage/ProposeCard.js
- src/components/MyPage/VideoWrapper.js
- src/pages/Mypage.js
- src/pages/OngoingSummit.js
- src/pages/Summit.js
Reverts 9oormthon-univ/2024_DANPOON_TEAM_36_FE#54
> Revert "feat : 20241123 1957"

- src/components/Summit/GotoUpload.js
- src/pages/Summit.js
- Summit 페이지 로그인 상태에 따른 모달창 이벤트
- localStorage 안에 accessToken 없으면 로그인 모달창 출력되게 설정
#53
> feat(Summit.js) : Summit 페이지 로그인 상태에 따른 모달창 이벤트

- src/components/NavigationBar.js
- src/pages/Main.js
- src/pages/Mypage.js
feat : navigation.js 로그인 상태에 대한 마이페이지 모달창 이벤트
#53
> Feat#53 login navigation

- src/constants/SummitMapTest.js
> docs : SummitMapTest pturl 추가

- src/components/OngoingSummit/Carousel.js
- src/components/OngoingSummit/UploadSuggestion.js
- src/pages/OngoingSummit.js
- src/pages/PT.js
- props dto 수정
- null값 처리하여 출력물 다르게 설정(삼항연산자)
#63
> Docs#63 dto ongoingsummit

- src/components/OngoingSummit/UploadSuggestion.js
- src/constants/SummitMapTest.js
> style, docs : uploadSuggestion 컴포넌트 margin 변경, SummitMapTest docs

- src/components/MyPage/Info.js
> style : info css 변경

- src/components/NavigationBar.js
navigation 로그아웃 클릭시 localStorage 삭제
#68
> feat(Navigation.js) : logout 클릭시 localStorage 삭제

- src/pages/PT.js
feat : PT 페이지에서 null 값 들어온 경우 예외처리
#72
> feat(PT.js) : null값 예외처리

- src/components/OngoingSummit/UploadSuggestion.js
컴포넌트 props 설정으로 'upload/{summitId}' 설정
> docs(UploadSuggestion.js) : props 지정

- src/apis/Board/saveBoard.js
- src/apis/Comment/saveComment.js
- src/apis/Feed/uploadImage.js
- src/apis/Investment/getMyInvest.js
- src/components/MyPage/LikePTVideo.js
- src/components/MyPage/MyPTVideo.js
- src/components/MyPage/ProposeCard.js
- src/components/OngoingSummit/Carousel.js
- src/components/PT/EditDelete.js
- src/components/Summit/GotoUpload.js
- src/pages/Mypage.js
- src/pages/OngoingSummit.js
- src/pages/PT.js
- src/pages/Summit.js
- src/pages/Upload.js
- src/routes.js
> Feat#42 summit ongoingsummit api
